# SciKit Learn Preprocessing Overview

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [6]:
data

array([[91, 80],
       [68, 71],
       [67,  7],
       [81, 14],
       [73, 99],
       [63, 59],
       [31, 36],
       [94,  6],
       [71,  8],
       [26, 19]])

In [9]:
scaler_model = MinMaxScaler()

In [28]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [12]:
scaler_model.transform(data)

array([[ 0.95588235,  0.79569892],
       [ 0.61764706,  0.69892473],
       [ 0.60294118,  0.01075269],
       [ 0.80882353,  0.08602151],
       [ 0.69117647,  1.        ],
       [ 0.54411765,  0.56989247],
       [ 0.07352941,  0.32258065],
       [ 1.        ,  0.        ],
       [ 0.66176471,  0.02150538],
       [ 0.        ,  0.13978495]])

In [30]:
# In one step
result = scaler_model.fit_transform(data)

In [31]:
result

array([[ 0.31313131,  0.91397849,  0.09090909,  0.77319588],
       [ 0.14141414,  0.46236559,  0.8989899 ,  0.40206186],
       [ 0.83838384,  0.84946237,  0.65656566,  0.70103093],
       [ 0.87878788,  0.10752688,  0.2020202 ,  0.07216495],
       [ 0.86868687,  0.77419355,  0.32323232,  0.34020619],
       [ 0.51515152,  0.20430108,  0.96969697,  0.07216495],
       [ 0.70707071,  0.29032258,  0.63636364,  0.67010309],
       [ 0.62626263,  0.06451613,  0.28282828,  0.45360825],
       [ 0.09090909,  0.70967742,  0.73737374,  0.08247423],
       [ 0.64646465,  0.69892473,  0.37373737,  0.8556701 ],
       [ 0.17171717,  0.61290323,  0.31313131,  0.4742268 ],
       [ 0.73737374,  0.43010753,  0.41414141,  0.04123711],
       [ 0.94949495,  0.92473118,  0.58585859,  0.82474227],
       [ 0.81818182,  0.15053763,  0.50505051,  0.51546392],
       [ 0.61616162,  0.11827957,  0.88888889,  0.90721649],
       [ 0.44444444,  1.        ,  0.07070707,  0.69072165],
       [ 0.16161616,  0.

In [15]:
import pandas as pd

In [16]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [24]:
data.head()

f1  f2  f3  label
0  79  12  96     29
1  35  75  39     84
2   5  61  62     87
3  97  85  76     69
4  67  65  30     64

In [17]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [18]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [25]:
X_train.shape

(35, 3)

In [23]:
X_test.shape

(15, 3)

In [26]:
y_train.shape

(35,)

In [27]:
y_test.shape

(15,)

## Great Job!